In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [4]:
dataset=pd.read_csv("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [10]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough') # all remaining columns that were not specified in transformers will be automatically passed through
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [14]:
#Feature Scaling(Always necessary for deep learning)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)



```
Building the ANN```



In [15]:
#initializing the ann

ann = tf.keras.models.Sequential()


In [16]:
#Adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))   #First hidden layer is added

In [17]:
#Adding second hidden layer

ann.add(tf.keras.layers.Dense(units=6,activation='relu')) 

In [18]:
#Adding output layer


ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) 

In [19]:
#Training the ann

#Compiling the ann

ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [20]:
#Training the ann on training set

ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.6300 - accuracy: 0.6593
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4387 - accuracy: 0.8009
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4312 - accuracy: 0.8065
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4257 - accuracy: 0.8131
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4221 - accuracy: 0.8177
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4191 - accuracy: 0.8204
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4167 - accuracy: 0.8186
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4142 - accura

In [21]:
#Making the predictions and evaluating the model

print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


In [23]:
# Predicting the Test set results
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1539   46]
 [ 217  198]]


0.8685